### ISSUE TITLE
Open Meat

### ISSUE THREAD

**Issue by K8Krueger** [MozillaFestival/open-leaders-6#111]
Finding different ways to grow food from cells instead of animals [Creating a muscle tissue bioreactor process design through bioreactor build and process design.]

**Comment by K8Krueger** [comment]
https://docs.google.com/presentation/d/1QstYXKqkksH3KAt0GcZDaWeKrX9KcwyOJl1kQzYfLyU/edit?usp=sharing

**Comment by K8Krueger** [comment]
**Roadmap**
Project Mission and Summary:

Our mission is to build open source bioreactors and process designs for making meat in the lab. We will create teams for a hackathon where we will kick off our designs of bioreactors and process designs. Teams will continue to work in a distributed fashion over Slack after the project has been completed. Completed bioreactors and process designs will be tested in different labs.

Milestones:

1.    December/January – sign up to join a team

                       2. January – teams form

                       3. February – the hackathon

      Tasks for each milestone:

1.    Publicize team signups

2.    Create a team slack.

3.    Plan and run the hackathon

a.    Find a venue

b.    Find a time

c.    Coordinate with volunteers to make it happen

Email kate@new-harvest.org to get involved.

**Comment by K8Krueger** [comment]
> Would be great to process the vision statement through the [Up Goer Five Text Editor](http://splasho.com/upgoer5/)!

Thanks for the suggestion!

**Comment by abbycabs** [comment]
closing for now
