### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Nefert** [MozillaFestival/open-leaders-6#113]
**African Citizen History Roadmap**
**_Tagline: What does Africa think of Africa_**

**Project  Mission**

_Working with Afrophiles to unearth and document most of precolonial African experiences, and re-imagine colonial and post-colonial African history through African lens. We hope to build a destination for alternative narratives about the continent and its cultures that Afrophiles and others can use to re-shape their perceptions of themselves and of the continent.

We are working open because; 1)we believe this is technically a public and shared resource,2) we believe the sheer scale of the project can only be achieved through collective intelligence, and 3)because we wish to develop a version that is not motivated by interests that hope to gain financially and politically by shaping the narrative a certain way._

 
**Milestone One**
 
October
 

- Build initial community
- Onboard at least 2 web developers 
- Onboard “CTO”
- Set up social media accounts
- Onboard a Social Media person
- Set up landing page to collect emails
- Onboard an events savvy person
- Develop User Terms of Engagement
- Develop “How To’s”

 
 
 
**Milestone Two**
 November

- Website
- Figure out hosting plan
- Design beta site
- Decide on website format/structure/architecture 
- Design how users can contribute
- Design search functionality

**Funding**

- Figure out how the project will be funded
- Develop fundraising plan

**Community**
Develop Social Media campaign

**Comment by abbycabs** [comment]
closing for now since it's not a project
