### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by Nefert** [MozillaFestival/open-leaders-6#114]
### What we are doing 
We are building a website where people interested in an alternative version of history of  Africa and its cultures can contribute to. 

### The Problem

There seems to be a consensus that a big chunk of what is known as African history was largely skewed to represent the interests of the powers that be at various points over the last one hundred plus years. 

Digital media(and the internet in general) and evolving interests and thoughts have seen the revelation, sharing and dissemination of information about the continent that was initially restricted to certain groups or individuals. Some of this information has brought into question a number of things that were taught as history.

### The Solution

In light of that, we feel like one platform-a website- where volunteers can collectively publish all these knowledge that is shared in bits on social media and other digital forums would not only provide a narrative that can shape another historical perspective but it would also harness this Pan-African spirit and provide a basis for people to re-imagine and re-construct new stories that could inform new identities. 

### Who we are

The who is currently taking shape. We will share the details when that has been figured out. 

This project is mentored by the Mozilla Open Leaders 2018. 

### What We Need

You, in any way you can contribute.

We need help with user experience design, website design and development, figuring out the search functionality, fundraising, community building/development, sourcing and documenting “stories” and any other way we might not have pointed out but whose need you can identify and feel can help address. For the time being, you can reach us by dropping us a [message on Twitter](https://twitter.com/assembliafrica) and we will be in touch. 

This ReadMe was based on the ReadMes of the [Open Body Database Project](https://github.com/openbodydatabase/obdb-project#the-problems), and the [STEMM Rode Models project](https://github.com/KirstieJane/STEMMRoleModels).

**Comment by abbycabs** [comment]
closing for now since it's not a project
