### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by Nefert** [MozillaFestival/open-leaders-6#118]
This project is about identity as much as it is about storytelling. Identity is about expression, both overt and covert and the inferences we make from it. We encourage all forms of expressions, as long as they end where the dignity and rights of others begin, unless they are shared and repeatedly consented to expressions. Our strength is in acknowledging the myriad of unique traits that make us individual but makes the group diverse.  

We welcome everyone who understands that, shares our beliefs, convictions and goals and believes that every individual regardless of sex/gender, race, background, sexual orientation deserves to be treated with respect. 

This code is aimed at making everyone feeling safe and comfortable so that they are at their best when contributing and participating in shared community projects. 

### Be respectful
Being respectful allows us to be honest, direct in our contributions and feedback without harming others. We should be mindful of our words/language and the context in which we use them. 

We should also be cognizant of how our behaviour impacts others and strive to behave in ways that do not cause harm or encourage others to cause harm but to encourage community, growth and cohesion. We can disagree without being hurtful or disrespectful. That is the mark of a mature mind.

Do not insult or put down other contributors. 

### Be professional
All communication and interaction should be within the parameters of what is considered as professional behaviour. No sexula language or imagery will be allowed. 

### No harassment 
We will not tolerate harassment of any form by/of members of the community. We hope to foster an harassment free experience for all members of the community.

**Comment by abbycabs** [comment]
closing for now since it's not a project
