### ISSUE TITLE
Cultural Literacy in Oakland County

### ISSUE THREAD

**Issue by alzellner** [MozillaFestival/open-leaders-6#14]
Project Lead: @alzellner

Mentors: @triaslucia, @denefi

**Comment by alzellner** [comment]
Here is my Vision Statement: I’m working with ELA Teachers to build capacity around diverse literature so that students are engaged with literature as windows and mirrors and sliding glass doors.

**Comment by owenjoseph** [comment]
Hi @alzellner!

Regarding your vision statement, this sounds like an exciting project. I’ve been working for Pearson Education for the past 5 years and my mother is an arts educator, so I can follow along, but I wonder if there are some terms that potential collaborators might find opaque. 

I thought the following phrases could use some unpacking:
- “ELA Teachers”
- “build[ing[ capacity”
- “literature as windows and mirrors and sliding glass doors”

Also, I think including a description of how you hope this project will impact the students could add clarity.

Cheers!

**Comment by alzellner** [comment]
Here is my Board: https://realtimeboard.com/welcomeonboard/kDJJbKf9YZ4xQXI31lcO3otrFzjujVch1K819xIDGnZB0dA18RRUtMyDXTtZFpZi

**Comment by abbycabs** [comment]
closing for now
