### ISSUE TITLE
Culture Development @ BuzzFeed

### ISSUE THREAD

**Issue by cotarg** [MozillaFestival/open-leaders-6#48]
Project Lead: cotarg

Mentor: Maya Wagoner

Welcome to OL6, Cohort E! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***
Before Week 1 (Sept 13): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Sept 20): First Cohort Call (Open by Design)
- [ ] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol6-syllabus-culture-track) for notes and connection info for all the cohort calls.

Before Week 3 (Sept 27): Mentorship call
- [ ] Look up two other projects and comment on their issues with feedback on their vision statement.
- [ ] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [ ] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Oct 4): Cohort Call (Build for Understanding)
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.
- [ ] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [ ] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

This issue is here to help you keep track of work during the first month of the program. Please refer to the [OL6 Syllabus](https://mzl.la/ol6-syllabus-culture-track) for more detailed weekly notes and assignments past week 4.

**Comment by cotarg** [comment]
I’m working with engineers at BuzzFeed to build and practice an open work culture supported by 'formal' process so that members of the tech community can build better, user-conscious stuff (aka 'the right things'). I want to work open because creation of culture is a community process, and I hope to both benefit from those who have come before and contribute tools, strategies, and ideas back to the ecosystem for others.

**Comment by bmuenzenmeyer** [comment]
I really like the mention of creating a formal process for this contribution. When conscious investment is made its so much easier for teams and individuals to feel empowered to give back. Nice work!

**Comment by ju-liem** [comment]
I love your mention of culture as a community process. My org went through a formal statement of community practices that was created by a group of people interested in codifying how we work and interact. It's an amazing touchstone to have, especially on the hard days.

**Comment by triaslucia** [comment]
User-conscious creation? couldn´t be better!! 
As a user-based designer  I´m so glad to see projects like yours 👍  
I´d love to hear more about it !!

**Comment by abbycabs** [comment]
closing for now
