### ISSUE TITLE
Learning Masters - Co-Creators of Open Education

### ISSUE THREAD

**Issue by marenff** [MozillaFestival/open-leaders-6#49]
Project Lead: @marenff

Mentor: @iceLearn

Welcome to OL6, Cohort B! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***
Before Week 1 (Sept 11): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.
 
Before Week 2 (Sept 18): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol6-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Sept 25): Mentorship call
- [ ] Look up two other projects and comment on their issues with feedback on their vision statement.
- [ ] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [ ] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Oct 2): Cohort Call (Build for Understanding)
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.
- [ ] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [ ] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

This issue is here to help you keep track of work during the first month of the program. Please refer to the [OL6 Syllabus](https://mzl.la/ol6-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by marenff** [comment]
Week 1 - mentorship call
About my project:
* Problem: contributions to open learning / education are limited to certain people. These people often identify as teachers (as opposed to students) or experts, feel comfortable using tech and being visible online. This limits the contributions, the diversity of the contributors, and therefore the quality of the online learning environment and experience. Online learning experience is also failing to include people who do not learn in a linear fashion. They often drop out of the provided online learning experiences that need you to follow a certain agenda.
* Goals:
   * Invite people to see themselves as masters as well as learners (we all have experience and knowledge that is valuable to others)
   * Create an easy to follow process for people to contribute (minimizing tech fears)
   * Be open to a diverse and inclusive approach to learning content

OLF Self-Assessment
What fit with what you already thought about your open leadership practice?
* That I'm at the beginning of this journey and have a lot to learn.

Which strengths made sense to you?
* Designing for Understanding and Sharing as well as Empower for Understanding and Sharing as these are practices that I use in my offline facilitation, training and coaching practice

Which areas of growth fit with that you expected?
* Having no experience in how to build a process that includes others to contribute.

What surprised you?
* That I actually am using already some of these practices.

Set 1-2 personal open leadership goals for yourself.
* Learning to create and communicate openly processes that empower people to participate and contribute

Set 1-2 goals for your project
Where do you want your project to be by the end of the program? (14 weeks)
Possible areas to think about:
* Community (Contributors / Maintainers / Members)
* Product (Launch / MVP / Feature)
* Resources / Sustainability (Governance / Funding / Gifts)
Goals
* Create and test a process to invite people to contribute and make it easy for them
* Learn and share about alternative ways of learning online (non-linear, inclusive, diverse) 

Anything else:
* MozFest
   * Self-directed participation and team as facilitators
   * Process created to contribute (as video with subtitles, audio, print)
   * Feedback about the process to learn for the project!!!

**Comment by marenff** [comment]
I have the idea for this project where people of all backgrounds can easily access online learning experiences, thereby educating themselves. I believe that all of these people are not just learners but also masters of something, a hobby, their culture, language, ... and that as masters in this field they can provide educational experiences around this topic to others. What I want to provide with this project is an environment that invites people to share themselves as masters as well as receive as learners, thereby creating an open learning and growth community.

**Comment by marenff** [comment]
First vision draft:
I am working with people who want to learn and share their expertise to provide a framework and environment in which they cn create and share peer-to-peer learning experiences.

Questions:
Who is my community?

**Comment by marenff** [comment]
My topics / communities:
- open and alternative education
- sustainability, especially Cradle to Cradle
- personal development
- coaching and facilitation

**Comment by tedarbyshire** [comment]
Hey, your vision statement sounds great. It might be worth looking at the access points for inclusion? You need time, support and internet access to get involved in this kind of project.

**Comment by marenff** [comment]
Open Canvas:
https://docs.google.com/presentation/d/1iF17V6CL0C41YDVRF150NCcMwPqzZMHHh7XzPpgEtY8/edit?usp=sharing

**Comment by hnstone** [comment]
As an educator I really like that you are working to support those who are approach learning in a non linear way and that you realize education comes in many forms. You have very lofty goals, and I can't wait to see how you work to achieve them.

**Comment by triaslucia** [comment]
Hey your project sound amazing !!! Empowering people as experts of their own expiriences, just great!  
I used to work on sustainablity more likely with Cradle to Cradle.. can´t wait so see more !!!

**Comment by Wentale** [comment]
Interesting project. I'll return here to see how you use GitHub to show processes or workflows.

**Comment by withshubh** [comment]
> Open Canvas:
> https://docs.google.com/presentation/d/1iF17V6CL0C41YDVRF150NCcMwPqzZMHHh7XzPpgEtY8/edit?usp=sharing

Hey,
Very well laid Open Canvas! 👍

**Comment by acabunoc** [comment]
Closing for now, see you in OL7 @marenff
