### ISSUE TITLE
Project Facet

### ISSUE THREAD

**Issue by HBCompass** [MozillaFestival/open-leaders-6#82]
Project Lead: @HBCompass

Mentor: @drashti4

Welcome to OL6, Cohort C! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Sept 12): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Sept 19): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol6-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Sept 26): Mentorship call
- [x] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [ ] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Oct 3): Cohort Call (Build for Understanding)
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.
- [ ] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [ ] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

This issue is here to help you keep track of work during the first month of the program. Please refer to the [OL6 Syllabus](https://mzl.la/ol6-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by HBCompass** [comment]
**Draft Vision Statement:**
I’m working with newsrooms, community organizations and community members to build the infrastructure and ecosystem of collaborative journalism so that newsrooms can best serve society with quality information informed by the involvement of partners empowered to participate in the editorial process.

I'm working open because true collaboration is made possible through transparency, trust and inclusivity.

**Comment by denefi** [comment]
Love this Project, I've been lookin at your blog and it's super interesting plus lots of cool resources. Looking forward to see ways of collaborating on your project!

**Comment by JazzBrotha** [comment]
Highly relevant in today's media circus. I really like your approach to working open.

**Comment by alzellner** [comment]
This is sort of tangential to your project, but one that has intrigued me in a similar space (although their users are news consumers rather than creators) is fiskkit: http://fiskkit.com/about

If you are interested in talking with them let me know!

**Comment by Nefert** [comment]
Love this! Ditto @JazzBrotha. There's this platform https://civil.co/. You might already be aware of it, if not, it might be of interest to you.

**Comment by HBCompass** [comment]
[Draft Open Canvas](https://docs.google.com/presentation/d/1Wy03degawp5BtLjdI4W6kgt6PvJDJoRPi4Z_NyAJNXA/edit?usp=sharing)

**Comment by acabunoc** [comment]
Closing for now, see you in OL7 @HBCompass!
